language: cpp
compiler: gcc

matrix:  
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libgmp-dev
            - libgmp10
            - libmpfr-dev
            - libmpfr4
      env:
        - MATRIX_EVAL="CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libgmp-dev
            - libgmp10
            - libmpfr-dev
            - libmpfr4
      env:
        - MATRIX_EVAL="CXX=g++-7"

before_install:
  - echo ${TRAVIS_JOB_NUMBER}
  - eval "${MATRIX_EVAL}"
  - uname -a  
  - ${CXX} --version  

script: 
  - make travisbuildversion rebuild smoke test version
  
