sudo: false
language: cpp
compiler: gcc
script: make test

matrix:  
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CXX=g++-6"

before_install:
  - eval "${MATRIX_EVAL}"